# -*- coding: utf-8 -*-
"""london_bike.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19GWw4QexNpI3kXpg4aFzUpGM-E7nZyiT
"""

!pip install kaggle
import pandas as pd
import zipfile

from google.colab import files
uploaded = files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

import kaggle

!kaggle datasets download -d hmavrodiev/london-bike-sharing-dataset

zipfile_name = '/content/london-bike-sharing-dataset.zip'
with zipfile.ZipFile(zipfile_name, 'r') as file:
  file.extractall()

bikes = pd.read_csv('london_merged.csv')

bikes.info()

bikes.shape

bikes

bikes.weather_code.value_counts()

bikes.season.value_counts()

new_cols_dict={
    'timestamp':'time',
    'cnt':'count',
    't1':'temp_real_C',
    't2':'temp_feels_like_C',
    'hum':'humidity_percent',
    'wind_speed':'wind_speed_kph',
    'weather_code':'weather',
    'is_holiday':'is_holiday',
    'is_weekend':'is_weekend',
    'season':'season'
}
bikes.rename(new_cols_dict, axis=1, inplace = True )

bikes.humidity_percent = bikes.humidity_percent / 100

season_dict = {
    '0.0':'spring',
    '1.0':'summer',
    '2.0':'autumn',
    '3.0':'winter'
}
weather_dict = {
    '1.0':'Clear',
    '2.0':'Scattered Clouds',
    '3.0':'Broken Clouds',
    '4.0':'Cloudy',
    '7.0':'Rain',
    '10.0':'Rain with thunderstorm',
    '26.0':'Snowfall'
}
bikes.season = bikes.season.astype('str')
bikes.season = bikes.season.map(season_dict)

bikes.weather = bikes.weather.astype('str')
bikes.weather = bikes.weather.map(weather_dict)

bikes.head()

bikes.to_excel('london_bikes_finals.xlsx',sheet_name = 'Data')